#!/bin/bash
#Chromebook chroot menu

# derive the supayuzamenyu installation dir
THISWORKINGDIR="$(dirname "$( readlink -f "$0")")"
# echo "This is the working directory: "
# echo $THISWORKINGDIR

# require the sample runcom
THISRCFILE="${THISWORKINGDIR}/supayuzamenyu.rc"
#load rc file
set -o xtrace
source $THISRCFILE
set +o xtrace


# PS3 – prompt used by “select” inside shell script
PS3='Please enter your choice (number): '

# menu options
options[0]="--Launch-- Minecraft (full Ubuntu in separate environment)"
options[1]="--Launch-- Ubuntu (full Ubuntu in Chrome window)"
options[2]="--Launch-- Terminal (Ubuntu terminal in Chrome tab)"
options[3]="--Quit menu--"

select opt in "${options[@]}"
do
	case $opt in
		"${options[0]}")
			sudo startxfce4 -X xorg
			break
			;;
		"${options[1]}")
			sudo startxfce4 -X xiwi
			break
			;;
		"${options[2]}")
			sudo bash ~/Downloads/supayuzamenyu-master/crouton-crucial-master/crucial.sh -c "xiwi -T xfce4-terminal"
			break
			;;
		"${options[3]}")
			break
			;;
		*) echo "Invalid option" ;;
	esac
done

