#!/bin/bash
#Chromebook chroot menu

# PS3 – prompt used by “select” inside shell script
PS3='Please enter your choice (number): '

£ menu options
options[0]="--Launch-- Minecraft (full Ubuntu in separate environment)"
options[1]="--Launch-- Ubuntu (full Ubuntu in Chrome window)"
options[2]="--Launch-- Terminal (Ubuntu terminal in Chrome tab)"
options[3]="--Quit menu--"

select opt in "${options[@]}"
do
	case $opt in
		"${options[0]}")
			sudo startxfce4 -X xorg
			;;
		"${options[1]}")
			sudo startxfce4 -X xiwi
			;;
		"${options[2]}")
			sudo bash ~/Downloads/crouton-crucial-master/crucial.sh -c "xiwi -T xfce4-terminal"
			;;
		"Quit")
			break
			;;
		*) echo "Invalid option" ;;
	esac
done

