#!/bin/bash -e
#Chromebook chroot menu

# derive the supayuzamenyu installation dir
THISWORKINGDIR="$(dirname "$( readlink -f "/usr/local/bin/menu")")"
# echo "This is the working directory: "
# echo $THISWORKINGDIR

# require the sample runcom
THISRCFILE="${THISWORKINGDIR}/supayuzamenyu.rc"
#load rc file
set -o xtrace
source $THISRCFILE
set +o xtrace

CRUCIALRCFILE="${THISWORKINGDIR}/${CRUCIALDESTINATIONDIR}/crucial.rc"
set -o xtrace
source $CRUCIALRCFILE
set +o xtrace


# PS3 – prompt used by “select” inside shell script
PS3='Please enter your choice (number): '

# menu options
options[0]="--Launch-- Full Ubuntu (full Ubuntu in separate environment)"
options[1]="--Launch-- Ubuntu (Ubuntu in Chrome window)"
options[2]="--Launch-- Terminal (Ubuntu terminal in Chrome tab)"
options[3]="--Launch-- An Ubuntu Application in a Tab (e.g. gimp)"
options[4]="--Launch-- An Ubuntu Application in a Window (e.g. gimp)"
options[5]="--Quit menu ------------------------------------------------"
options[6]="--Delete-- Delete Ubuntu (deletes all instances of Ubuntu)"
options[7]="--Create-- Create a NEW Ubuntu (this takes a long while then launches in Chrome Window)"

clear

select opt in "${options[@]}"
do
	case $opt in
		"${options[0]}")
			sudo "${CRSTARTCMD}" -X xorg
			break
			;;
		"${options[1]}")
			sudo "${CRSTARTCMD}" -X xiwi
			break
			;;
		"${options[2]}")
			sudo bash "${THISWORKINGDIR}"/"${CRUCIALDESTINATIONDIR}"/crucial.sh -c "xiwi -T xfce4-terminal"
			break
			;;
		"${options[3]}")
			echo "Type application name e.g bash or gimp then [ENTER]:"
			read APPLICATION
			sudo enter-chroot xiwi -T "${APPLICATION}"
			break
			;;
		"${options[4]}")
			echo "Type application name e.g bash or gimp then [ENTER]:"
			read APPLICATION
			sudo enter-chroot xiwi -F "${APPLICATION}"
			break
			;;
		"${options[5]}")
			break
			;;
		"${options[6]}")
			sudo edit-chroot -d "${CRRELEASE}"
			break
			;;
		"${options[7]}")
			sudo bash "${THISWORKINGDIR}"/"${CRUCIALDESTINATIONDIR}"/crucial.sh -i
			break
			;;
		*) echo "Invalid option" ;;
	esac
done

