#!/bin/bash -e
#Chromebook menu

# PS3 – prompt used by “select” inside shell script
PS3='Please enter your choice (number): '

# menu options
options[0]="--Install-- Minecraft Game"
options[1]="--Install-- Eclipse Integrated Development Editor"
options[2]="--Install-- Gimp Image Editor"
options[3]="--Install-- Alacarte Ubuntu Menu builder"
options[4]="--Quit menu ------------------------------------------------"

cd ~
clear

select opt in "${options[@]}"
do
	case $opt in
		"${options[0]}")
			sh /usr/local/bin/target_files/minecraft.sh
			break
			;;
		"${options[1]}")
			sh /usr/local/bin/target_files/eclipse.sh
			break
			;;
		"${options[2]}")
			sh /usr/local/bin/target_files/gimp.sh
			break
			;;
		"${options[3]}")
			sh /usr/local/bin/target_files/alacarte.sh
			break
			;;
		"${options[4]}")
			break
			;;
		*) echo "Invalid option" ;;
	esac
done

